### ISSUE TITLE
waystation paper

### ISSUE THREAD

**Issue by softloud** [softloud/nmareporting#12]
## structure of ms

link to current draft

## who does what

Current proposal:

who | what
-|-
everyone | 3x discussion, 2 weeks (?) apart
matt, david | example toolchains (#14 #13 ) according to MECIR standards
hollie, gav | discussion of project, lit on reporting, affect vs effect

> How should the meetings  be spaced?

## authorship

Ask collabs for best way. 

> Opt-in from discussions?

## tasks

- [ ] look into how to make a contribution matrix
- [ ] number of studies per outcome
- [ ] hash authors with starwars & drugs with lotr

## questions

- what about multiple outcomes, how does this affect reporting?
- look at the PRISMA ext paper, this is the main thing
